### ISSUE TITLE
regex for checking java version isn't supported for Java SE

### ISSUE THREAD

**Issue by pranavsdev** [MagedSaeed/farasapy#10] opened 2020-11-15 00:21 UTC
Issue: 

I get below error when I initialise FarasaSegmenter

File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/farasa/__base.py", line 149, in _check_java_version
    re.search(version_pattern, version_proc_output).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

Below are the details for java version on my machine.

$ java -version
java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)

Possible cause: Seems that regular expression is not handling Java SE. It supports only jdk
Locally I am able to run it using version_pattern = r'\"(.+?)\"'

**Comment by MagedSaeed** [comment] 2020-11-15 06:41
Thanks for mentioning that @greenshrek 

Regarding your solution, I think `r"'(.+?)"'` pattern is more than what is required? what about `r"\"(\d+)*\"`? This will check there is at least a version digits. What do you think?

One more issue that needs to be implemented is this should not stop the flow. Instead, the exception should be caught and returned with a proper error message.

**Comment by greenshrek** [comment] 2020-11-16 01:24
Hi @MagedSaeed 

1) regex r"\"(\d+)*\" will work fine if there is only a major version involved. However, it fails where there is a minor version and a patch also in version_proc_output (example - 13.01.01). Attached is the code for reference (check.py)

[check.py.zip](https://github.com/MagedSaeed/farasapy/files/5543558/check.py.zip)

2) Yes, agree. The flow should not be stopped.

**Comment by rrpelgrim** [comment] 2021-03-31 18:55
Hi @MagedSaeed and @pranavsdev - has this been solved? I'm running into the same issue with:

`java -version
java version "16" 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)`

**Comment by MagedSaeed** [comment] 2021-04-01 11:56
Hey @pranavsdev , 

Thanks for reporting such issue. Just give me some time. I will try to fix it as soon as possible.

**Comment by rrpelgrim** [comment] 2021-04-01 14:20
Great, thank you. Would you please notify me when you've fixed it so I know
when I can continue working?

Best,

--
*Richard Pelgrim*
+31 (0)6 374 807 31

**Comment by MagedSaeed** [comment] 2021-04-02 15:44
@rrpelgrim I am currently working on it. The cause of the problem is that the regex will match any java version with this pattern "d.d+" However, I was not expecting to receive patterns like "d+".

I had tested this pattern 
```
version_pattern = r"\"(\d+(\.\d+){0,1})"
```
and seemed to work just fine.

@pranavsdev , I just found out that you replied to this issue with the code. Thanks for your effort. I need your thoughts both here on the proposed regex. Regarding the one you proposed, I do not feel it is restrictive. I feel this is more restrictive.

**Comment by MagedSaeed** [comment] 2021-04-02 15:44
If you both agreed to this regex, I will update the code and push the changes to both, the GitHub repo and PyPi.

**Comment by pranavsdev** [comment] 2021-04-02 16:36
@MagedSaeed 

version_pattern = r"\"(\d+(\.\d+){0,1})" is not able to match a pattern like - 13.01.01

Instead, version_pattern = r"(\d+(\.\d+){0,1})" works fine for me. It is able to match 13 or 13.01 or 13.01.01

I used https://regex101.com/ to test. Please check the attachments.

![3](https://user-images.githubusercontent.com/40683895/113435009-4980c580-93e2-11eb-9bd9-3cbd9a2a84da.png)
![2](https://user-images.githubusercontent.com/40683895/113435011-4a195c00-93e2-11eb-8dab-442789254c96.png)
![1](https://user-images.githubusercontent.com/40683895/113435012-4ab1f280-93e2-11eb-8535-308915a6e7a8.png)

**Comment by MagedSaeed** [comment] 2021-04-02 17:28
Actually, this should not work. Because you are missing the " character at the beginning. I noticed that every version starts with ". So, I want to only match the version exactly excluding any other possibility for other numbers. I only matched two tokens split by '.'. This is because I want to compare it with 1.7.

![image](https://user-images.githubusercontent.com/18549783/113438698-c7989880-93f1-11eb-83a1-c4beaa255ed8.png)


Yours will accept any character between numbers including '_'. Because you are not escaping the '.'.

Hope you got may point!

**Comment by pranavsdev** [comment] 2021-04-02 17:39
Ah, i missed that. You are right, it should work!!

**Comment by ALahssini** [comment] 2021-04-15 14:12
Hi @MagedSaeed and @pranavsdev - has this been solved? 

I'm trying to use Farasa segmenter on openjdk docker image with java SE.

Thank you in advance for your answer !

**Comment by MagedSaeed** [comment] 2021-04-16 01:12
Hey @ALahssini  and @rrpelgrim 

I fixed the problem locally but figured out that I did not deploy to PyPI. I just pushed changes to GitHub and also deployed to PyPI. Please uninstall your current version, I guess 0.0.12, and install the latest one, 0.0.13 by :

```
pip install -U farasapy
```

Let me know if the problem did not resolve,.

Maged,.

**Comment by MagedSaeed** [comment] 2021-04-16 01:12
Please let me know so that I will close this issue.

**Comment by MagedSaeed** [comment] 2021-04-24 11:14
@ALahssini  and @rrpelgrim 

Any updates please, if you do not have any comments, I will close this issue.

**Closed** 2021-06-10 15:01 UTC
Labels: bug
